#ifndef  RF_SEXP_OUTGOING_H
#define  RF_SEXP_OUTGOING_H
#define SG_CPU_TIME   0  
#define SG_MEMB_ID        1  
#define SG_BOOT_CT        2  
#define SG_LEAF_CT        3  
#define SG_SEED_ID        4  
#define SG_TREE_ID        5  
#define SG_NODE_ID        6  
#define SG_NODE_SZ        7  
#define SG_BR_NODE_ID     8  
#define SG_PR_NODE_ID     9  
#define SG_BSF_ORD       10  
#define SG_PARM_ID       11  
#define SG_CONT_PT       12  
#define SG_MWCP_SZ       13  
#define SG_MWCP_PT       14  
#define SG_MWCP_CT       15  
#define SG_FS_REC_ID     16  
#define SG_NODE_STAT     17  
#define SG_RMBR_TN_CT    18  
#define SG_IMBR_TN_CT    19  
#define SG_OMBR_TN_CT    20  
#define SG_RMBR_TN_ID    21  
#define SG_IMBR_TN_ID    22  
#define SG_OMBR_TN_ID    23  
#define SG_NLSN_TN       24  
#define SG_HAZR_TN       25  
#define SG_NLSN_IBG      26  
#define SG_HAZR_IBG      27  
#define SG_HAZR_RAW_IBG  28  
#define SG_NLSN_OOB      29  
#define SG_HAZR_OOB      30  
#define SG_HAZR_RAW_OOB  31  
#define SG_T_HAZ_TM_IDX  32  
#define SG_T_HAZ_TM_CNT  33  
#define SG_RISK_IBG      34  
#define SG_RISK_OOB      35  
#define SG_RISK_RAW_IBG  36  
#define SG_RISK_RAW_OOB  37  
#define SG_ENSB_ID       38  
#define SG_NODE_RISK     39  
#define SG_NODE_RISK_RAW 40  
#define SG_TREE_RISK_IBG     41  
#define SG_TREE_RISK_OOB     42  
#define SG_TREE_RISK_RAW_IBG 43  
#define SG_TREE_RISK_RAW_OOB 44  
#define SG_IBG_SZ_CASE       45  
#define SG_OOB_SZ_CASE       46  
#define SG_WCASE_IBG         47  
#define SG_WCASE_OOB         48  
#define SG_WCASE_LEFT_ABS    49  
#define SG_WCASE_RIGHT_ABS   50  
#define SG_NODE_U            51  
#define SG_NODE_V            52  
#define SG_NODE_COE          53  
#define SG_NODE_CUMULATIVE_COE 54  
#define SG_COE_HAZR_TREE_IBG 55  
#define SG_COE_CHF_TREE_IBG  56  
#define SG_COE_HAZR_TREE_OOB 57  
#define SG_COE_CHF_TREE_OOB  58  
#define SG_COE_TRIM_INDEX    59  
#define SG_COE_TRIM_RISK_OOB 60  
#define SG_OPT_LO_GROW       61  
#define SG_OPT_HI_GROW       62  
#define SG_SEXP_SIZE         63  
extern char  *SG_sexpStringOutgoingCDL[];
extern char  *SG_sexpStringOutgoing[];
#endif
